action_set: "full"
players: ""
level: "11_vs_11_stochastic"
custom_display_stats: null
display_game_stats: false
episodes: 1
dump_full_episodes: true
dump_scores: false
physics_steps_per_frame: 10
render_resolution_x: 1280
render_resolution_y: 720
real_time: false
tracesdir: "/tmp/dumps"
video_format: "avi"
video_quality_level: 0
write_video: true
write_segmentation_video: true
write_instance_segmentation_video: true
write_ball_coordinates: true
game_engine_random_seed: 42
display_settings:
  radar: true
  scoreboard: true
  player_names: true
camera: "wide"
